version: '3.2'
services:
  redis:
    image: redis:latest
    container_name: redis1
    volumes:
    - "/root/ds_fs/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:Z"
    - "/root/ds_fs/redis/logs:/var/log/redis:Z"
    - "/root/ds_fs/redis/db:/var/lib/redis:Z"
    entrypoint:
    - redis-server
    - /usr/local/etc/redis/redis.conf
    - --requirepass
    - breach12345
    ports:
    - "6379:6379"
  ds:
    image: git.trustwave.com:4567/ops-containers/spring-boot:latest
    container_name: ds1
    ports:
    - "8080:8080"
    - "8010:8010"
    - "9010:9010"
    - "9107:9107"
    - "8778:8778"
    volumes:
    - "${DS_FOLDER_PREFIX}/etc/nepa-dserver/base.properties:/etc/nepa-dserver/base.properties:Z"
    - "${DS_FOLDER_PREFIX}/etc/nepa-dserver/application.properties:/etc/nepa-dserver/application.properties:Z"
    - "${DS_FOLDER_PREFIX}/etc/nepa-dserver/management.properties:/etc/nepa-dserver/management.properties:Z"    
    - "${DS_FOLDER_PREFIX}/var/log/nepa-dserver/:/var/log/nepa-dserver/:Z"
    - "${DS_FOLDER_PREFIX}/var/lib/nepa-dserver/nepa-dserver-${DS_VERSION}.war:/var/lib/nepa-dserver/nepa-dserver.jar:Z"
    - "${DS_FOLDER_PREFIX}/var/lib/nepa-dserver/agent_binaries/latest/windows10/x64/current:/var/lib/nepa-dserver/agent_binaries/latest/windows10/x64/current:Z"
    environment:
    - CONF_FILE_FULL_NAME=/etc/nepa-dserver/application.properties
    - PROPERTY_KEY=l4twtestpw
    command: ["-jar", "/var/lib/nepa-dserver/nepa-dserver.jar"]

    depends_on:
    - redis